apiVersion: v1
name: artifactory-ha
home: https://www.jfrog.com/artifactory/
version: 0.8.3
appVersion: 6.6.3
description: Universal Repository Manager supporting all major packaging formats,
  build tools and CI servers.
keywords:
- artifactory
- jfrog
- devops
sources:
- https://bintray.com/jfrog/product/JFrog-Artifactory-Pro/view
- https://github.com/jfrog/charts
maintainers:
- name: zhangwei
  email: wei.zhang@i-soft.com.cn
icon: https://raw.githubusercontent.com/jfrog/artifactory-dcos/master/images/jfrog_med.png
